import React from 'react'
import './Contact.css'
const Contacts = () => {
  return (
    <div className='contact__'>,
      <div className='container__contact'>
        <h2>What is Lorem Ipsum?</h2>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique provident dolores quia libero dolorum adipisci in! Veritatis dolore esse, cupiditate suscipit dolores nam earum est aliquid possimus dolor, nulla explicabo hic? A fugit corrupti itaque possimus, labore suscipit eius impedit maiores incidunt voluptate non nisi similique eaque, corporis sint beatae deleniti, totam eum! Quisquam aperiam quis ducimus fuga repudiandae laudantium optio cumque totam. Quasi soluta sequi accusantium nam eligendi! Perspiciatis omnis ab eaque adipisci, beatae necessitatibus nesciunt commodi rem sequi officiis illo odio, quos quae tempora doloribus quaerat assumenda! Delectus, accusantium suscipit fugit consequatur in doloremque nisi aperiam, ullam natus eligendi quo totam, possimus obcaecati optio excepturi voluptate ea cumque alias necessitatibus corporis? Maiores rerum mollitia minus reiciendis non sapiente odio ea facilis cum, culpa animi accusantium et iusto illum. Incidunt minus, commodi unde excepturi rem animi reiciendis, repellat repudiandae fugiat totam esse est repellendus quae nostrum iste nobis quam! Dicta dolores necessitatibus impedit consequuntur voluptate, eligendi minima dolore totam provident? Necessitatibus accusamus, nihil, hic explicabo vel ex perspiciatis illo ab obcaecati blanditiis, molestias laboriosam in rem. Earum quos qui soluta! A, totam minima reprehenderit sit ratione soluta rem debitis quisquam reiciendis perferendis. Sequi cum recusandae, eveniet ipsa repellendus rem modi quas, esse, debitis facilis aliquam voluptatum explicabo pariatur placeat voluptate fugiat cupiditate quaerat inventore tempore reprehenderit aspernatur laboriosam! Quos magni ipsum rerum cumque quaerat, sunt reprehenderit nihil. Quas magnam non quisquam facere beatae laudantium dolore. Ipsa rem totam asperiores obcaecati temporibus, quis consectetur dignissimos eveniet dolorum, saepe vitae enim debitis, sequi illo error? Quaerat voluptate, voluptas fugit adipisci ipsum magnam reprehenderit officia alias quo, voluptatum veritatis, odio nobis similique? Cumque dicta deserunt rerum laboriosam non sint, dolore nostrum eligendi labore, a officia cum fugiat cupiditate nulla culpa sed odit iure quasi. Sapiente enim optio nesciunt necessitatibus dignissimos possimus ea.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique provident dolores quia libero dolorum adipisci in! Veritatis dolore esse, cupiditate suscipit dolores nam earum est aliquid possimus dolor, nulla explicabo hic? A fugit corrupti itaque possimus, labore suscipit eius impedit maiores incidunt voluptate non nisi similique eaque, corporis sint beatae deleniti, totam eum! Quisquam aperiam quis ducimus fuga repudiandae laudantium optio cumque totam. Quasi soluta sequi accusantium nam eligendi! Perspiciatis omnis ab eaque adipisci, beatae necessitatibus nesciunt commodi rem sequi officiis illo odio, quos quae tempora doloribus quaerat assumenda! Delectus, accusantium suscipit fugit consequatur in doloremque nisi aperiam, ullam natus eligendi quo totam, possimus obcaecati optio excepturi voluptate ea cumque alias necessitatibus corporis? Maiores rerum mollitia minus reiciendis non sapiente odio ea facilis cum, culpa animi accusantium et iusto illum. Incidunt minus, commodi unde excepturi rem animi reiciendis, repellat repudiandae fugiat totam esse est repellendus quae nostrum iste nobis quam! Dicta dolores necessitatibus impedit consequuntur voluptate, eligendi minima dolore totam provident? Necessitatibus accusamus, nihil, hic explicabo vel ex perspiciatis illo ab obcaecati blanditiis, molestias laboriosam in rem. Earum quos qui soluta! A, totam minima reprehenderit sit ratione soluta rem debitis quisquam reiciendis perferendis. Sequi cum recusandae, eveniet ipsa repellendus rem modi quas, esse, debitis facilis aliquam voluptatum explicabo pariatur placeat voluptate fugiat cupiditate quaerat inventore tempore reprehenderit aspernatur laboriosam! Quos magni ipsum rerum cumque quaerat, sunt reprehenderit nihil. Quas magnam non quisquam facere beatae laudantium dolore. Ipsa rem totam asperiores obcaecati temporibus, quis consectetur dignissimos eveniet dolorum, saepe vitae enim debitis, sequi illo error? Quaerat voluptate, voluptas fugit adipisci ipsum magnam reprehenderit officia alias quo, voluptatum veritatis, odio nobis similique? Cumque dicta deserunt rerum laboriosam non sint, dolore nostrum eligendi labore, a officia cum fugiat cupiditate nulla culpa sed odit iure quasi. Sapiente enim optio nesciunt necessitatibus dignissimos possimus ea.</p>

      </div>
    </div>
  )
}

export default Contacts
